openapi: 3.0.1
info:
  title: Node Cdx Bom
  description: >-
    Generate a unique, recursively merged SBOM for NodeJS projects and
    monorepos.
  x-cortex-git:
    github:
      repository: JupiterOne/node-cdx-bom
  x-cortex-owners:
    - type: group
      name: JupiterOne/sre
  x-cortex-tag: node-cdx-bom
  x-cortex-service-groups:
    - tier-4
